FROM tiangolo/uvicorn-gunicorn:python3.8

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

RUN pip install \
    titiler.core==0.3.* \
    titiler.mosaic==0.3.* \
    psycopg2

COPY src/eoapi/raster /tmp/raster
RUN pip install /tmp/raster
RUN rm -rf /tmp/raster

ENV MODULE_NAME eoapi.raster.app
ENV VARIABLE_NAME app
