ARG PYTHON_VERSION=3.9

FROM tiangolo/uvicorn-gunicorn:python${PYTHON_VERSION}

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

RUN pip install \
    titiler.core==0.4.* \
    titiler.mosaic==0.4.* \
    psycopg[binary,pool]

COPY src/eoapi/raster /tmp/raster
RUN pip install /tmp/raster
RUN rm -rf /tmp/raster

ENV MODULE_NAME eoapi.raster.app
ENV VARIABLE_NAME app
