ARG PYTHON_VERSION=3.9

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

COPY src/eoapi/vector /tmp/vector
RUN pip install /tmp/vector
RUN rm -rf /tmp/vector

ENV MODULE_NAME eoapi.vector.app
ENV VARIABLE_NAME app
