ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

COPY src/eoapi/vector /tmp/vector
RUN pip install /tmp/vector
RUN rm -rf /tmp/vector

COPY src/eoapi/vector/custom /tmp/functions

ENV MODULE_NAME eoapi.vector.app
ENV VARIABLE_NAME app
ENV TIPG_CUSTOM_SQL_DIRECTORY /tmp/functions
