ARG PYTHON_VERSION=3.10

FROM public.ecr.aws/lambda/python:${PYTHON_VERSION}

WORKDIR /tmp

ARG PGSTAC_VERSION

WORKDIR /tmp
RUN python -m pip install pip -U

RUN echo "Using PGSTAC Version ${PGSTAC_VERSION}"
RUN python -m pip install httpx psycopg["binary,pool"] pypgstac==${PGSTAC_VERSION} -t /asset

COPY infrastructure/aws/handlers/db_handler.py /asset/handler.py

# https://stackoverflow.com/a/61746719
# Turns out, asyncio is part of python
RUN rm -rf /asset/asyncio*

CMD ["echo", "hello world"]
