import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
            <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
              Permissions
            </p>
            <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center ">
              <a
                className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
                href="https://developmentseed.org?utm_source=eoAPI&utm_medium=eoAPI-spicedb-ui&utm_campaign=eoAPI-spicedb-ui"
                target="_blank"
                rel="noopener noreferrer"
              >
                eoAPI by DevelopmentSeed
              </a>
            </div>
          </div>

          <div className="mb-32 grid text-center lg:text-left bg-gradient-to-t from-white via-white dark:from-black dark:via-black">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
