ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

COPY runtime/eoapi/stac /tmp/stac
RUN pip install /tmp/stac
RUN rm -rf /tmp/stac

ENV MODULE_NAME eoapi.stac.app
ENV VARIABLE_NAME app
