ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

ARG INSTALL_EXTRA=

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

COPY runtime/eoapi/stac /app/stac
RUN pip install -e "/app/stac${INSTALL_EXTRA}"

ENV MODULE_NAME eoapi.stac.app
ENV VARIABLE_NAME app
