site_name: The Earth Observation API
site_description: Create a full Earth Observation API with Metadata, Raster and Vector services.

docs_dir: 'src'
site_dir: 'build'

repo_name: "developmentseed/eoAPI"
repo_url: "https://github.com/developmentseed/eoAPI"

extra:
  analytics:
    provider: plausible
    domain: eoapi.dev
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/developmentseed"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/development-seed"
    - icon: "fontawesome/solid/rss"
      link: "https://developmentseed.org/blog"

nav:
  - Home: index.md
  - Getting started:
    - intro.md
    - Services: services.md
    - Contributing: contributing.md
  - Advanced User Guide:
    - Customization: customization.md
  - Deployment: deployment.md

plugins:
  - search
extra_css:
  - overrides/stylesheets/extra.css
theme:
  name: material
  custom_dir: src/overrides/
  palette:
    primary: custom
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.sections
  favicon: img/favicon.ico
  logo: img/logo.png

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
