ARG PYTHON_VERSION=3.9

FROM public.ecr.aws/lambda/python:${PYTHON_VERSION}

WORKDIR /tmp

ARG PGSTAC_VERSION

WORKDIR /tmp
RUN pip install pip -U

RUN echo "Using PGSTAC Version ${PGSTAC_VERSION}"
RUN pip install requests psycopg["binary"] pypgstac==${PGSTAC_VERSION} -t /asset

COPY stack/handlers/db_handler.py /asset/handler.py

# https://stackoverflow.com/a/61746719
# Turns out, asyncio is part of python
RUN rm -rf /asset/asyncio*

CMD ["echo", "hello world"]
